### ISSUE TITLE
TclError: no display name and no $DISPLAY environment variable

### ISSUE THREAD

**Issue by chonnymon** [dupontgu/retro-ipod-spotify-client#10]
Hello, Firstly thanks for sharing this awesome project.

I receive the error below after trying to run `python3 spotifypod.py`
This error appeared after I entered the redirected URL

Can anyone point me in the right direction to get past this?

`Traceback (most recent call last):
  File "spotifypod.py", line 543, in <module>
    app = tkinterApp()
  File "spotifypod.py", line 88, in __init__
    tk.Tk.__init__(self, *args, **kwargs)
  File "/usr/lib/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable`

Thanks

**Comment by dupontgu** [comment]
I think I remember seeing this at some point. Are you SSHing into the pi?  `python3 spotifypod.py` needs to be run by a non-remote user, and the pi needs to detect a display (though it will work if you enable the composite video output). If that doesn't solve it, I'd start poking around for related issues with `tkinter` - this is thrown from that code, not mine. Hope that helps!

**Comment by chonnymon** [comment]
Thanks for your quick reply, Yes I was SSHing into the pi, after running the script from root@ I have got the UI to display on my monitor, it will show what I currently have playing under 'now playing' on my account but doesn't display anything under artists/albums/new releases

**Comment by rsappia** [comment]
@chonnymon run refresh_data() method and it will sync all your content ;)
