### ISSUE TITLE
Compiling click.c warnings

### ISSUE THREAD

**Issue by Archipollo** [dupontgu/retro-ipod-spotify-client#13]
Hello, so I tried compiling the click.c with the command supplied in the file :'gcc -Wall -pthread -o click click.c -lpigpio -lrt'.
The problem is I'm getting two error messages and I don't know anything about C, so I don't know how to fix them.
The errors are:
click.c:160:5: warning: first argument of 'main' should be 'int' [-Wmain]
 int main(void *args){
      ^~~~
click.c:160:5: warning: 'main' takes only zero or two arguments [-Wmain]

Can somebody help me, Pigpio is installed and I'm guessing it has to do something with the main function, but I don't know how to fix this.

**Comment by rsappia** [comment]
@Archipollo it is just a warning, look in the directory, you should find the compiled file nex to to the .c ;)

**Comment by Archipollo** [comment]
Ah yes I see, thank you!
