### ISSUE TITLE
No License?

### ISSUE THREAD

**Issue by Seshpenguin** [dupontgu/retro-ipod-spotify-client#27]
Hey,
Unless I missed it, there is no open source license for the code?
If that's the case then the code is technically proprietary (I assume that's not what you want). I am not a lawyer but from what I know right now people can't legally modify, distribute, or use your code (incl. to make contributions) without your written consent each time ([See this github doc](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license)).

Personally, I'd use the GNU GPL (so people can't take your code and create a closed source version) but you may prefer something else 😄

**Comment by dupontgu** [comment]
Went with Apache, but thanks for the reminder!
