### ISSUE TITLE
Enable Discussions Tab

### ISSUE THREAD

**Issue by tomaculum** [dupontgu/retro-ipod-spotify-client#42]
Hi @dupontgu,

could you please enable the *Discussions* tab in the repository settings? Instead of creating new issues, this would be a better place to ask questions.

**Comment by tomaculum** [comment]
Here is a link to githubs documentation with instructions to enable this tab: https://docs.github.com/en/discussions/quickstart

**Comment by dupontgu** [comment]
Good idea, done.
