### ISSUE TITLE
Search infinitely loading.

### ISSUE THREAD

**Issue by MattDB101** [dupontgu/retro-ipod-spotify-client#54]
After battling for a weekend I'm finally nearing the end of the software side of things.

The only thing that I cannot seem to get working is the search function.

I was originally having issues with actually playing any songs from my playlists until I modified the scope array in spotify_manager.py. Am I missing anything from my scope that is causing my search issues? 

Here's my current scope:
```
 scope = "user-follow-read," \
        "user-library-read," \
        "user-library-modify," \
        "user-modify-playback-state," \
        "user-read-playback-state," \
        "user-read-currently-playing," \
        "app-remote-control," \
        "playlist-read-private," \
        "playlist-read-collaborative," \
        "playlist-modify-public," \
        "playlist-modify-private," \
        "streaming," \
        "user-read-private"
```

I am able to play music from my playlists, and at this stage, I'm happy to just leave it at that, but if I could get the search function working too, that would be great.

**Comment by MattDB101** [comment]
I've successfully solved half my problem, I can now auto boot to spotifypod.py. 
To anyone facing a similar issue to what I described; It was a simple mistake in the autostart.

I followed these instructions from issue #9:

> Run "spotifypod.py" with autostart

> sudo nano /etc/xdg/openbox/autostart
> and add the following command to launch spotifypod.py:
> cd /home/pi/fork/retro-ipod-spotify-client/frontend/
> sudo -H -u pi python3 spotifypod.py >> spotifypod.log &
> sudo /home/pi/fork/retro-ipod-spotify-client/clickwheel/click &

> Make sure that the paths are ok with your setup!!

**^ I left /fork/ in the path by mistake. ^**

So, that solves half my problem. 
I still am unable to play anything or search for songs though, so any help would be greatly appreciated.

**Comment by hushdauihdhi** [comment]
Did you ever end up finding the fix to this?

**Comment by mattbyrn** [comment]
> Did you ever end up finding the fix to this?

Unfortunately not, I've totally scrapped the project for now.

**Comment by doris1347** [comment]
MattDB101 - Do  I read you correctly in saying that you were able to correct not being able to play tracks from any of your playlist until you added the 'Scope"  ("user-read-private")? and if yes did the Spotifypod.py GUI screen take a long time to load and appear?
Thanks!

**Comment by mattbyrn** [comment]
I can't recall anymore sorry. I shelved the project for now, hoping to come back to it at some point in the future. Will update here if I ever have an answer to this
