### ISSUE TITLE
AutoStart seems to not work

### ISSUE THREAD

**Issue by xenon0054** [dupontgu/retro-ipod-spotify-client#65]
Hello when I start my pi up the display is black. I think I've looked every on the page and can't seem to find an answer

have any suggestions?

**Comment by doris1347** [comment]
Do you have a mouse cursor? (if yes) What happens when you right click on the black screen?

**Comment by xenon0054** [comment]
when I right click I get a menu that just says open terminal emulator, open browser, etc

**Comment by doris1347** [comment]
Can you upload photo's of your below files:
1) sudo nano /etc/xdg/openbox/environment
2) sudo nano /etc/xdg/openbox/autostart
3) sudo nano /etc/X11/xinit/xinitrc

**Comment by xenon0054** [comment]
### /etc/xdg/openbox/environment
![environment](https://user-images.githubusercontent.com/76131600/179846715-ffc3d2cc-975c-43bb-884b-8de1ee312e7d.jpg)

### /etc/xdg/openbox/autostart
![autostart](https://user-images.githubusercontent.com/76131600/179848122-ec67fa5b-8557-4907-ba4e-e370c1431445.PNG)

###  /etc/X11/xinit/xinitrc
![xinitrc](https://user-images.githubusercontent.com/76131600/179846344-754f40d6-7f42-4bf3-af6d-c5ee72939aae.PNG)

**Comment by doris1347** [comment]
I had a similar problem and added to your below file 2 bottom last entry lines:
sudo nano /etc/xdg/openbox/environment

cd/home/xero/retro-ipod-spotify-client/frontend
python3 spotifypod.py &

No forward slash ('/") after frontend ... Then reboot and it worked !

**Comment by doris1347** [comment]
Has your "Spot" ever worked for you?

**Comment by xenon0054** [comment]
Nope it never has. 

So I added the new line you told me and it still doesn't auto run the file

**Comment by doris1347** [comment]
two lines !!

**Comment by xenon0054** [comment]
Yeah I added both lines:
![a](https://user-images.githubusercontent.com/76131600/179854011-fd20b0ca-2ddc-48e3-9090-ac6beb451b43.jpg)

**Comment by doris1347** [comment]
my autostart only has two lines:

cd /home/pi/retro-ipod-spotify-client/frontend

sudo -H -u pi --preserve-env=SPOTIPY_REDIRECT_URl,SPOTIPY_CLIENT_ID,SPOTIPY_CLIENT_SECRET, python3 spotifypod.py &

**Comment by doris1347** [comment]
My Environment minus the private stuff:

SCOPE = "user-follow-read," \
        "user-library-read," \
        "user-library-modify," \
        "user-modify-playback-state," \
        "user-read-playback-state," \
        "user-read-currently-playing," \
        "app-remote-control," \
        "playlist-modify," \
        "playlist-read-private," \
        "playlist-read-collaborative," \
        "playlist-modify-public," \
        "playlist-modify-private," \
        "streaming," \
        "user-follow-modify," \
        "user-follow-read"


cd /home/pi/retro-ipod-spotify-client/frontend

sudo /home/pi/retro-ipod-spotify-client/clickwheel/click &

python3 spotifypod.py &

**Comment by doris1347** [comment]
Our "sudo nano /etc/X11/xinit/xinitrc"  are identical!

**Comment by xenon0054** [comment]
let me modify my environment to look similar to yours and and see if it works

**Comment by doris1347** [comment]
okay I'm at my computer now waiting for you

**Comment by doris1347** [comment]
yours has to be after home/xero mine is home/pi

**Comment by xenon0054** [comment]
oh yeah, thanks almost forgot going to reboot again

**Comment by doris1347** [comment]
change you autostart to look exactly like mine as well!

**Comment by doris1347** [comment]
I also have spaces between my lines

**Comment by xenon0054** [comment]
Yeah it worked! but the clickwheel driver didn't start so going to put it back in the auto start and see if it works with it.

**Comment by doris1347** [comment]
that always breaks things for me!

**Comment by xenon0054** [comment]
yeah as soon as I add it it doesn't work.

**Comment by doris1347** [comment]
send a few photo's of your breakout board wiring if you used one and did you compile click.c ?

**Comment by doris1347** [comment]
Do you or did you work at Xerox?

**Comment by xenon0054** [comment]
> send a few photo's of your breakout board wiring if you used one and did you compile click.c ?

Yes I did compile it

![image](https://user-images.githubusercontent.com/76131600/179857269-1070175d-827a-47cd-a713-6dd8e4c76b6f.jpeg)

And no I never worked at Xerox

**Comment by doris1347** [comment]
Your breakout board wiring may be incorrect can you send photo of the reverse side

**Comment by doris1347** [comment]
I'm retired from Xerox

**Comment by xenon0054** [comment]
The wiring is correct it does display it just displays darkness.

You used to work at xerox never heard of them before what did you do?

**Comment by doris1347** [comment]
Field Engineer

**Comment by doris1347** [comment]
what to you mean it displays?

**Comment by xenon0054** [comment]
What I mean is when I go and right click it it shows the menu. It just doesn't run the spotifypod.py file on boot.

Was it hard to be a Field Technician?

**Comment by doris1347** [comment]
I used the 2"Adafriut display with composite video input

**Comment by xenon0054** [comment]
for my display I followed these instructions from [rsflights](http://rsflightronics.com/spotifypod#Wiring_the_Display)

**Comment by doris1347** [comment]
I am a certified Electronics Technician so no it wasn't hard for me

**Comment by xenon0054** [comment]
wow, but how come you don't work there anymore if it wasn't hard for you?

**Comment by doris1347** [comment]
I'm not clear on what worked below:

"Yeah it worked! but the clickwheel driver didn't start so going to put it back in the auto start and see if it works with it."

Your breakout board wiring may be incorrect can you send photo of the reverse side

**Comment by xenon0054** [comment]
The spotifypod.py file booted but the clickwheel isn't working anymore.

Wow, your 70 years old! your pretty smart most people I know who are 70 don't know how to use a tv.

**Comment by doris1347** [comment]
I Built a color TV from a kit (Heathkit) when I was17 years old

**Comment by doris1347** [comment]
Are you saying that the clickwheel was working?

**Comment by XEROxMEXICANO** [comment]
you built a tv before! Is it similar to this one?
![s-l1600](https://user-images.githubusercontent.com/76131600/179860521-ad3558d8-8f2b-4ac8-9c83-d51af977d7d8.jpg)

**Comment by xenon0054** [comment]
Uh not the clickwheel does not work anymore.
it no longer auto starts

**Comment by doris1347** [comment]
how did you know the clickwheel was working?

**Comment by xenon0054** [comment]
I ssh into the pi and manually started the spotifypod.py file and moved it around

**Comment by doris1347** [comment]
my clickwheel works with the entries I sent you

**Comment by xenon0054** [comment]
really? let me take a second look at the code and see if I messed up

**Comment by doris1347** [comment]
how old are you?

**Comment by xenon0054** [comment]
I'm 17 years old

**Comment by doris1347** [comment]
Ah I see I have a granddaughter your age

**Comment by doris1347** [comment]
I built 6 Heathkit GR-2001 25" color TV's when I was 17 and a Complete Heathkit SB401 SB-303 with accessories Amateur Radio Station

**Comment by doris1347** [comment]
I can't help you with your IPS Display, however can't understand why your clickwheel isn't working if it was before!

**Comment by xenon0054** [comment]
Wow you built a ton of stuff.

I can't understand why it doesn't work anymore either, I think I'm just going to take a break and come back later to try and fix it

**Comment by doris1347** [comment]
Taking a break always works for me ... Good Luck! & Stay Focused

**Comment by xenon0054** [comment]
Thanks you so much for the help!! Hope you have a great rest of your day/night!!

**Comment by doris1347** [comment]
Remove all the Scopes from "sudo nano /etc/xdg/openbox/environment"
