### ISSUE TITLE
How to add a new option on the menu page

### ISSUE THREAD

**Issue by xenon0054** [dupontgu/retro-ipod-spotify-client#70]
Where you would usually find playlists, albums, and podcasts I want to make a new one called Pair Audio so when it's clicked it will run subprocess.run(["btaudio-connect"]) which will run a bash command in python that connects my headphones.

My headphones already connect upon boot, But sometimes they don't or they are connected to my phone so I wanted an easy option to connect my headphones. I already have the code displaying the option but can't get it to run when clicked, I have no experience in python just messing around and looking at how the other classes get processed.

Here's what I already got working:
![pair_head](https://user-images.githubusercontent.com/76131600/208824734-b655aa83-78a4-4662-a314-415d7e7d1dd0.png)
with this code
![Code_head](https://user-images.githubusercontent.com/76131600/208824929-ffa60294-750e-450b-85fd-432044bb3390.png)
![run_head](https://user-images.githubusercontent.com/76131600/208825425-100f8cea-a9f8-4879-aa8b-19da9e1a4eba.png)
When I click on it, it freezes the program and I have to restart and it's back to normal. Any ideas?

**Comment by doris1347** [comment]
Make one for WiFi as well !!! 😊✅

**Comment by doris1347** [comment]
Great Bluetooth Audio Stuff !!! 😊

https://github.com/introt/docs/issues/5

**Comment by doris1347** [comment]
Best Bluealsa Installation Instructions Link:

[https://introt.github.io/docs/raspberrypi/bluealsa.htm](https://introt.github.io/docs/raspberrypi/bluealsa.html)

**Comment by xenon0054** [comment]
Thank you!, I will continue to work on this later, unfortunately I'm busy all morning today.

**Comment by doris1347** [comment]
I'm taking a "Python" Course I'm sure I will figure it out! 😉

**Comment by doris1347** [comment]
Michael ... it isn't necessary to insert "Device ID's" in the code!
Just be  sure Guy Dupont's  "Instructions Step #12" and the below are correct!:

def refresh_devices():
    device = UserDevice('id,'device_name', is_active)
    DATASTORE.setUserDevice(device)
    for _, item in enumerate(results['devices']):
        if "Spotifypod" in item['name']:
            print(item['name'])
            device = UserDevice(item['id'], item['name'], item['is_active'])
            DATASTORE.setUserDevice(device)

I removed all device ID's from the code.
**Still works correctly!**

**Comment by doris1347** [comment]
I managed to upgrade Raspotify 0.31.8 To "Bullseye" any higher then 0.31.8 and the "sPoT" couldn't find "sPotiPy".

**Comment by doris1347** [comment]
You may want to review closed issue 44 it looks like others has already accomplished what your trying to do and more see below closed thread:

https://github.com/nboumalham/retro-ipod-spotify-client

**Comment by doris1347** [comment]
However it looks like Spotifyd is used instead of Raspotify

**Comment by doris1347** [comment]
I got the above fork version working using Raspotify (didn't need SpotifyD) this version does have a bluetooth switcher!

**Comment by doris1347** [comment]
By studying the above Bluetooth switcher code you probably could get your Bluetooth selection icon working.

**Comment by HannesBro** [comment]
Did you achieve anything concerning the new menu? Unfortunately there is no answer and the question itself is so interesting...
