### ISSUE TITLE
electric schemes 

### ISSUE THREAD

**Issue by giusedm** [dupontgu/retro-ipod-spotify-client#8]
You did a great job congratulations! , I was wondering if you can add connection schemes so maybe we can too.

**Comment by dupontgu** [comment]
Yup, I have uploaded them as a build log on the hackaday.io page:
https://hackaday.io/project/177034-spot-spotify-in-a-4th-gen-ipod-2004/log/189343-wiring

I will also add to this repo this evening.

**Comment by giusedm** [comment]
thank you very much, great job

**Comment by giusedm** [comment]
i modified kakoub's schema found on hackaday.io if there are some errors, please tell me
![bx0WM4p](https://user-images.githubusercontent.com/66377237/108607492-0a159100-73c1-11eb-9a93-91b9f6bd1295.jpg)

**Comment by dupontgu** [comment]
That looks correct to me, just make sure you put the clickwheel flex cable in the right way!

**Comment by giusedm** [comment]
ok thanks for the advice

**Comment by Archipollo** [comment]
Thank you very much for the detailed schematics! I just have one question. In @dupontgu 's Video he mentioned connecting the enable pin from the boost module to the hold switch, creating a power switch. So how would I need to connect the cables to do to the same? 

The enable Pin to the right side of the hold switch and the left side of the switch to ground?

**Comment by rsappia** [comment]
> i modified kakoub's schema found on hackaday.io if there are some errors, please tell me
> ![bx0WM4p](https://user-images.githubusercontent.com/66377237/108607492-0a159100-73c1-11eb-9a93-91b9f6bd1295.jpg)
> 
> 

It is a good practice to connect a diode in parallel with inductive loads (the motir in this case)  in order to protect the transistor.  I am preparing an updated version for SPI display and power management. Will upload as soon as i am done with testing!

**Comment by rsappia** [comment]
> Thank you very much for the detailed schematics! I just have one question. In @dupontgu 's Video he mentioned connecting the enable pin from the boost module to the hold switch, creating a power switch. So how would I need to connect the cables to do to the same? 
> 
> The enable Pin to the right side of the hold switch and the left side of the switch to ground? 

You will need some extra electronic in order to use the EN pin in a meaningful way if you want to wait until the RPI is done with the power up/ down cycle
